### PR TITLE
Russian translation and readme improvements

### PR DESCRIPTION
**Pull request by Blueberryy**
Added Russian translation for addon and readme.
Changed language links
Added extra translateable string for hack ``seconds``

### CODE REVIEW

**Comment by pilot22** [comment]
Thanks for your PR.

**Review by pilot22 — CHANGES_REQUESTED** [review]
@Blueberryy Need a translation please :)

**Review by pilot22 — CHANGES_REQUESTED** [review]
On that commit sorry

**Comment by Blueberryy** [comment]
Done!

**Review by pilot22 — APPROVED** [review]

**Comment by pilot22** [comment]
Thanks!

**Pull request merged**
